spring:
  application:
    name: huahai-ai-app-create-backend
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  profiles:
    active: dev # 指定运行环境

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  # redis
  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}
      password: ${spring.data.redis.password}
      database: ${spring.data.redis.database}
      ttl: 3600

server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.huahai.huahaiaiappcreate.controller
# knife4j 的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${langchain4j.open-ai.chat-model.api-key}
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
# 暂时注释掉 json 结构化输出特性， 保证 AI 选择生成文件类型的流程成功运行
#      strict-json-schema: true
#      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${langchain4j.open-ai.streaming-chat-model.api-key}
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
    # 推理 AI 模型配置（用于复杂的推理任务）
    reasoning-streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${langchain4j.open-ai.reasoning-streaming-chat-model.api-key}
      model-name: deepseek-reasoner
      max-tokens: 32768
      temperature: 0.1
      log-requests: true
      log-responses: true
    # 智能路由 AI 模型配置（用于简单的分类任务）
    routing-chat-model:
      base-url: https://api.deepseek.com
      api-key: ${langchain4j.open-ai.routing-chat-model.api-key}
      model-name: deepseek-chat
      log-requests: true
      log-responses: true


